/**
 * Resource — `recondo://reports/{id}` (D-C12-7).
 *
 * Returns a single compliance report row by id. Reports are
 * audit-side artefacts (rows in the `reports` table) generated by
 * the `recondo_generate_report` action tool — they do not contain
 * user-captured content, so no `<captured_*>` envelope wrapping is
 * applied here.
 */
import { getReport } from "@recondo/data";
import type { ApiKeyInfo } from "@recondo/data";

import type { AuthContext } from "../auth/context.js";
import type { ResourceDefinition, ResourceReadResult } from "./types.js";

export const REPORT_URI_TEMPLATE = "recondo://reports/{id}";
const URI_PREFIX = "recondo://reports/";

function authContextToApiKey(auth: AuthContext): ApiKeyInfo {
  return {
    id: auth.keyId,
    projectId: auth.projectId,
    rateLimitRpm: 0,
  };
}

function parseReportId(uri: string): string {
  if (!uri.startsWith(URI_PREFIX)) {
    throw new Error(
      `URI '${uri}' does not match the reports resource template '${REPORT_URI_TEMPLATE}'`,
    );
  }
  const id = uri.slice(URI_PREFIX.length);
  if (id.length === 0) {
    throw new Error(
      `reports resource URI is missing the {id} placeholder; got '${uri}'`,
    );
  }
  return id;
}

export const reportResource: ResourceDefinition = {
  uriTemplate: REPORT_URI_TEMPLATE,
  name: "reports",
  description:
    "A single Recondo compliance report row by id. Reports are audit-side artefacts produced by the recondo_generate_report action tool.",
  mimeType: "application/json",
  async read(uri, ctx): Promise<ResourceReadResult> {
    const id = parseReportId(uri);
    const apiKey = authContextToApiKey(ctx.auth);
    const report = await getReport(apiKey, id, { signal: ctx.abortSignal });
    if (report === null) {
      return {
        contents: [
          {
            uri,
            mimeType: "application/json",
            text: JSON.stringify({ error: "report_not_found", report_id: id }),
          },
        ],
        isError: true,
      };
    }
    return {
      contents: [
        {
          uri,
          mimeType: "application/json",
          text: JSON.stringify({ report }),
        },
      ],
    };
  },
};
