apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-gateway
  labels:
    app.kubernetes.io/name: recondo-gateway
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  replicas: {{ .Values.gateway.replicas }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app.kubernetes.io/name: recondo-gateway
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: recondo-gateway
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ .Release.Name }}-gateway
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
      volumes:
        - name: recondo-data
          emptyDir: {}
        - name: tmpdir
          emptyDir: {}
      containers:
        - name: gateway
          image: "{{ .Values.gateway.image.repository }}:{{ .Values.gateway.image.tag | default .Chart.AppVersion }}"
          securityContext:
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          imagePullPolicy: {{ .Values.gateway.image.pullPolicy }}
          volumeMounts:
            - name: recondo-data
              mountPath: /home/recondo/.recondo
            - name: tmpdir
              mountPath: /tmp
          ports:
            - name: gateway
              containerPort: 8443
              protocol: TCP
          env:
            - name: RECONDO_STORE
              value: {{ .Values.store.backend | default "postgres" }}
            - name: RECONDO_DB_URL
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secrets
                  key: postgres-uri
            - name: RECONDO_OBJECTS
              value: {{ .Values.objects.backend }}
            - name: RECONDO_S3_BUCKET
              value: {{ .Values.objects.s3Bucket }}
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8443
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8443
            initialDelaySeconds: 15
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 3
          resources:
            {{- toYaml .Values.gateway.resources | nindent 12 }}
      {{- with .Values.gateway.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.gateway.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.gateway.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
