apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-gateway
  labels:
    app.kubernetes.io/name: recondo-gateway
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: {{ .Values.gateway.service.type }}
  ports:
    - port: {{ .Values.gateway.service.port }}
      targetPort: 8443
      protocol: TCP
      name: gateway
  selector:
    app.kubernetes.io/name: recondo-gateway
    app.kubernetes.io/instance: {{ .Release.Name }}
