apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-gateway
  labels:
    app.kubernetes.io/name: recondo-gateway
    app.kubernetes.io/instance: {{ .Release.Name }}
  {{- if .Values.gateway.serviceAccount }}
  {{- if .Values.gateway.serviceAccount.annotations }}
  annotations:
    {{- toYaml .Values.gateway.serviceAccount.annotations | nindent 4 }}
  {{- end }}
  {{- end }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-operator
  labels:
    app.kubernetes.io/name: recondo-operator
    app.kubernetes.io/instance: {{ .Release.Name }}
